import { test, expect } from "@playwright/test";
import { sign } from "hono/jwt";
import * as fs from "fs";

// Try to parse .env file
try {
  const envFile = fs.readFileSync(".env", "utf-8");
  for (const line of envFile.split("\n")) {
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1];
      let value = match[2];
      if (value.startsWith('"') && value.endsWith('"'))
        value = value.slice(1, -1);
      process.env[key] = value;
    }
  }
} catch (e) {
  // ignore
}

test.describe("Admin Dashboard UI Tests", () => {
  // Test authentication boundary
  test("Dashboard is protected without session cookie", async ({ page }) => {
    await page.goto("/admin");
    await expect(page).toHaveURL("/login");
  });

  // Mocked authenticated state (assuming admin setup is complete normally)
  test.describe("Authenticated routes", () => {
    test.beforeEach(async ({ context }) => {
      // Set a valid test token generated by Hono
      const validToken = await sign(
        {
          id: "test-admin-id",
          type: "admin",
          exp: Math.floor(Date.now() / 1000) + 60 * 60, // 1 hour
        },
        process.env.JWT_SECRET || "super-secret-default-key",
        "HS256",
      );

      await context.addCookies([
        {
          name: "admin_session",
          value: validToken,
          domain: "127.0.0.1",
          path: "/",
        },
      ]);
    });

    test("Dashboard layout has dynamic new collection sidebar functionality", async ({
      page,
    }) => {
      // Goto admin
      await page.goto("/admin");

      // wait for htmx
      await page.waitForFunction(() => (window as any).htmx !== undefined);

      // Click 'New Collection'
      await page.click('button[title="New Collection"]');

      // wait for some time for HTMX to fire
      await page.waitForTimeout(1000);

      // Verify drawer slides out
      const drawer = page.locator("#drawer-container").locator("> div");
      await expect(drawer).toBeVisible();
      // Ensure 'New Collection' header is there
      await expect(page.locator('h2:has-text("New Collection")')).toBeVisible();

      // Ensure field interaction works
      await page.click('button:has-text("+ New Field")');
      const numberOfFields = await page.locator(".field-name").count();
      expect(numberOfFields).toBeGreaterThan(1);
    });
  });
});
